-- Generated by packages/kernel/scripts/catalog-search-migration.ts from the versioned document policy.
CREATE VIRTUAL TABLE catalog_search USING fts5(
  item_id UNINDEXED,
  kind UNINDEXED,
  document_version UNINDEXED,
  fingerprint UNINDEXED,
  slug,
  title,
  description,
  facets,
  latin_slug,
  latin_title,
  latin_description,
  latin_facets,
  tokenize = 'unicode61',
  prefix = '2 3'
);
--> statement-breakpoint
CREATE VIEW catalog_search_source AS
SELECT
  item.id AS item_id,
  item.kind AS kind,
  item.slug AS slug,
  item.name AS title,
  item.description AS description,
  trim(
    coalesce((SELECT group_concat(value, ' ') FROM (SELECT category.name AS value FROM catalog_item_categories membership JOIN categories category ON category.id = membership.category_id WHERE membership.catalog_item_id = item.id AND category.state = 'active' ORDER BY category.position, category.name, category.id)), '') || ' ' ||
    coalesce((SELECT group_concat(value, ' ') FROM (SELECT collection.name AS value FROM catalog_item_collections membership JOIN collections collection ON collection.id = membership.collection_id WHERE membership.catalog_item_id = item.id AND collection.state = 'active' ORDER BY collection.name, collection.id)), '') || ' ' ||
    coalesce((SELECT group_concat(value, ' ') FROM (SELECT tag.label AS value FROM catalog_item_tags membership JOIN tags tag ON tag.id = membership.tag_id WHERE membership.catalog_item_id = item.id AND tag.state = 'active' ORDER BY tag.label, tag.id)), '') || ' ' ||
    coalesce((SELECT group_concat(value, ' ') FROM (SELECT option_value.label AS value FROM variants variant JOIN variant_option_values membership ON membership.variant_id = variant.id JOIN option_values option_value ON option_value.id = membership.option_value_id JOIN option_groups option_group ON option_group.id = option_value.option_group_id WHERE variant.product_id = item.id AND variant.state = 'active' AND option_value.state = 'active' AND option_group.state = 'active' ORDER BY option_group.position, option_value.position, option_value.label, option_value.id)), '')
  ) AS facets
FROM catalog_items item
WHERE item.state = 'published';
--> statement-breakpoint
CREATE VIEW catalog_search_documents AS
WITH
  catalog_search_normalization_1 AS (
    SELECT
      item_id, kind,
      replace(replace(replace(replace(slug, 'ё', 'ё'), 'Ё', 'Ё'), 'й', 'й'), 'Й', 'Й') AS slug,
      replace(replace(replace(replace(title, 'ё', 'ё'), 'Ё', 'Ё'), 'й', 'й'), 'Й', 'Й') AS title,
      replace(replace(replace(replace(description, 'ё', 'ё'), 'Ё', 'Ё'), 'й', 'й'), 'Й', 'Й') AS description,
      replace(replace(replace(replace(facets, 'ё', 'ё'), 'Ё', 'Ё'), 'й', 'й'), 'Й', 'Й') AS facets
    FROM catalog_search_source
  ),
  catalog_search_normalization_2 AS (
    SELECT
      item_id, kind,
      replace(replace(replace(replace(slug, '０', '0'), '１', '1'), '２', '2'), '３', '3') AS slug,
      replace(replace(replace(replace(title, '０', '0'), '１', '1'), '２', '2'), '３', '3') AS title,
      replace(replace(replace(replace(description, '０', '0'), '１', '1'), '２', '2'), '３', '3') AS description,
      replace(replace(replace(replace(facets, '０', '0'), '１', '1'), '２', '2'), '３', '3') AS facets
    FROM catalog_search_normalization_1
  ),
  catalog_search_normalization_3 AS (
    SELECT
      item_id, kind,
      replace(replace(replace(replace(slug, '４', '4'), '５', '5'), '６', '6'), '７', '7') AS slug,
      replace(replace(replace(replace(title, '４', '4'), '５', '5'), '６', '6'), '７', '7') AS title,
      replace(replace(replace(replace(description, '４', '4'), '５', '5'), '６', '6'), '７', '7') AS description,
      replace(replace(replace(replace(facets, '４', '4'), '５', '5'), '６', '6'), '７', '7') AS facets
    FROM catalog_search_normalization_2
  ),
  catalog_search_normalization_4 AS (
    SELECT
      item_id, kind,
      replace(replace(replace(replace(slug, '８', '8'), '９', '9'), 'Ａ', 'A'), 'Ｂ', 'B') AS slug,
      replace(replace(replace(replace(title, '８', '8'), '９', '9'), 'Ａ', 'A'), 'Ｂ', 'B') AS title,
      replace(replace(replace(replace(description, '８', '8'), '９', '9'), 'Ａ', 'A'), 'Ｂ', 'B') AS description,
      replace(replace(replace(replace(facets, '８', '8'), '９', '9'), 'Ａ', 'A'), 'Ｂ', 'B') AS facets
    FROM catalog_search_normalization_3
  ),
  catalog_search_normalization_5 AS (
    SELECT
      item_id, kind,
      replace(replace(replace(replace(slug, 'Ｃ', 'C'), 'Ｄ', 'D'), 'Ｅ', 'E'), 'Ｆ', 'F') AS slug,
      replace(replace(replace(replace(title, 'Ｃ', 'C'), 'Ｄ', 'D'), 'Ｅ', 'E'), 'Ｆ', 'F') AS title,
      replace(replace(replace(replace(description, 'Ｃ', 'C'), 'Ｄ', 'D'), 'Ｅ', 'E'), 'Ｆ', 'F') AS description,
      replace(replace(replace(replace(facets, 'Ｃ', 'C'), 'Ｄ', 'D'), 'Ｅ', 'E'), 'Ｆ', 'F') AS facets
    FROM catalog_search_normalization_4
  ),
  catalog_search_normalization_6 AS (
    SELECT
      item_id, kind,
      replace(replace(replace(replace(slug, 'Ｇ', 'G'), 'Ｈ', 'H'), 'Ｉ', 'I'), 'Ｊ', 'J') AS slug,
      replace(replace(replace(replace(title, 'Ｇ', 'G'), 'Ｈ', 'H'), 'Ｉ', 'I'), 'Ｊ', 'J') AS title,
      replace(replace(replace(replace(description, 'Ｇ', 'G'), 'Ｈ', 'H'), 'Ｉ', 'I'), 'Ｊ', 'J') AS description,
      replace(replace(replace(replace(facets, 'Ｇ', 'G'), 'Ｈ', 'H'), 'Ｉ', 'I'), 'Ｊ', 'J') AS facets
    FROM catalog_search_normalization_5
  ),
  catalog_search_normalization_7 AS (
    SELECT
      item_id, kind,
      replace(replace(replace(replace(slug, 'Ｋ', 'K'), 'Ｌ', 'L'), 'Ｍ', 'M'), 'Ｎ', 'N') AS slug,
      replace(replace(replace(replace(title, 'Ｋ', 'K'), 'Ｌ', 'L'), 'Ｍ', 'M'), 'Ｎ', 'N') AS title,
      replace(replace(replace(replace(description, 'Ｋ', 'K'), 'Ｌ', 'L'), 'Ｍ', 'M'), 'Ｎ', 'N') AS description,
      replace(replace(replace(replace(facets, 'Ｋ', 'K'), 'Ｌ', 'L'), 'Ｍ', 'M'), 'Ｎ', 'N') AS facets
    FROM catalog_search_normalization_6
  ),
  catalog_search_normalization_8 AS (
    SELECT
      item_id, kind,
      replace(replace(replace(replace(slug, 'Ｏ', 'O'), 'Ｐ', 'P'), 'Ｑ', 'Q'), 'Ｒ', 'R') AS slug,
      replace(replace(replace(replace(title, 'Ｏ', 'O'), 'Ｐ', 'P'), 'Ｑ', 'Q'), 'Ｒ', 'R') AS title,
      replace(replace(replace(replace(description, 'Ｏ', 'O'), 'Ｐ', 'P'), 'Ｑ', 'Q'), 'Ｒ', 'R') AS description,
      replace(replace(replace(replace(facets, 'Ｏ', 'O'), 'Ｐ', 'P'), 'Ｑ', 'Q'), 'Ｒ', 'R') AS facets
    FROM catalog_search_normalization_7
  ),
  catalog_search_normalization_9 AS (
    SELECT
      item_id, kind,
      replace(replace(replace(replace(slug, 'Ｓ', 'S'), 'Ｔ', 'T'), 'Ｕ', 'U'), 'Ｖ', 'V') AS slug,
      replace(replace(replace(replace(title, 'Ｓ', 'S'), 'Ｔ', 'T'), 'Ｕ', 'U'), 'Ｖ', 'V') AS title,
      replace(replace(replace(replace(description, 'Ｓ', 'S'), 'Ｔ', 'T'), 'Ｕ', 'U'), 'Ｖ', 'V') AS description,
      replace(replace(replace(replace(facets, 'Ｓ', 'S'), 'Ｔ', 'T'), 'Ｕ', 'U'), 'Ｖ', 'V') AS facets
    FROM catalog_search_normalization_8
  ),
  catalog_search_normalization_10 AS (
    SELECT
      item_id, kind,
      replace(replace(replace(replace(slug, 'Ｗ', 'W'), 'Ｘ', 'X'), 'Ｙ', 'Y'), 'Ｚ', 'Z') AS slug,
      replace(replace(replace(replace(title, 'Ｗ', 'W'), 'Ｘ', 'X'), 'Ｙ', 'Y'), 'Ｚ', 'Z') AS title,
      replace(replace(replace(replace(description, 'Ｗ', 'W'), 'Ｘ', 'X'), 'Ｙ', 'Y'), 'Ｚ', 'Z') AS description,
      replace(replace(replace(replace(facets, 'Ｗ', 'W'), 'Ｘ', 'X'), 'Ｙ', 'Y'), 'Ｚ', 'Z') AS facets
    FROM catalog_search_normalization_9
  ),
  catalog_search_normalization_11 AS (
    SELECT
      item_id, kind,
      replace(replace(replace(replace(slug, 'ａ', 'a'), 'ｂ', 'b'), 'ｃ', 'c'), 'ｄ', 'd') AS slug,
      replace(replace(replace(replace(title, 'ａ', 'a'), 'ｂ', 'b'), 'ｃ', 'c'), 'ｄ', 'd') AS title,
      replace(replace(replace(replace(description, 'ａ', 'a'), 'ｂ', 'b'), 'ｃ', 'c'), 'ｄ', 'd') AS description,
      replace(replace(replace(replace(facets, 'ａ', 'a'), 'ｂ', 'b'), 'ｃ', 'c'), 'ｄ', 'd') AS facets
    FROM catalog_search_normalization_10
  ),
  catalog_search_normalization_12 AS (
    SELECT
      item_id, kind,
      replace(replace(replace(replace(slug, 'ｅ', 'e'), 'ｆ', 'f'), 'ｇ', 'g'), 'ｈ', 'h') AS slug,
      replace(replace(replace(replace(title, 'ｅ', 'e'), 'ｆ', 'f'), 'ｇ', 'g'), 'ｈ', 'h') AS title,
      replace(replace(replace(replace(description, 'ｅ', 'e'), 'ｆ', 'f'), 'ｇ', 'g'), 'ｈ', 'h') AS description,
      replace(replace(replace(replace(facets, 'ｅ', 'e'), 'ｆ', 'f'), 'ｇ', 'g'), 'ｈ', 'h') AS facets
    FROM catalog_search_normalization_11
  ),
  catalog_search_normalization_13 AS (
    SELECT
      item_id, kind,
      replace(replace(replace(replace(slug, 'ｉ', 'i'), 'ｊ', 'j'), 'ｋ', 'k'), 'ｌ', 'l') AS slug,
      replace(replace(replace(replace(title, 'ｉ', 'i'), 'ｊ', 'j'), 'ｋ', 'k'), 'ｌ', 'l') AS title,
      replace(replace(replace(replace(description, 'ｉ', 'i'), 'ｊ', 'j'), 'ｋ', 'k'), 'ｌ', 'l') AS description,
      replace(replace(replace(replace(facets, 'ｉ', 'i'), 'ｊ', 'j'), 'ｋ', 'k'), 'ｌ', 'l') AS facets
    FROM catalog_search_normalization_12
  ),
  catalog_search_normalization_14 AS (
    SELECT
      item_id, kind,
      replace(replace(replace(replace(slug, 'ｍ', 'm'), 'ｎ', 'n'), 'ｏ', 'o'), 'ｐ', 'p') AS slug,
      replace(replace(replace(replace(title, 'ｍ', 'm'), 'ｎ', 'n'), 'ｏ', 'o'), 'ｐ', 'p') AS title,
      replace(replace(replace(replace(description, 'ｍ', 'm'), 'ｎ', 'n'), 'ｏ', 'o'), 'ｐ', 'p') AS description,
      replace(replace(replace(replace(facets, 'ｍ', 'm'), 'ｎ', 'n'), 'ｏ', 'o'), 'ｐ', 'p') AS facets
    FROM catalog_search_normalization_13
  ),
  catalog_search_normalization_15 AS (
    SELECT
      item_id, kind,
      replace(replace(replace(replace(slug, 'ｑ', 'q'), 'ｒ', 'r'), 'ｓ', 's'), 'ｔ', 't') AS slug,
      replace(replace(replace(replace(title, 'ｑ', 'q'), 'ｒ', 'r'), 'ｓ', 's'), 'ｔ', 't') AS title,
      replace(replace(replace(replace(description, 'ｑ', 'q'), 'ｒ', 'r'), 'ｓ', 's'), 'ｔ', 't') AS description,
      replace(replace(replace(replace(facets, 'ｑ', 'q'), 'ｒ', 'r'), 'ｓ', 's'), 'ｔ', 't') AS facets
    FROM catalog_search_normalization_14
  ),
  catalog_search_normalization_16 AS (
    SELECT
      item_id, kind,
      replace(replace(replace(replace(slug, 'ｕ', 'u'), 'ｖ', 'v'), 'ｗ', 'w'), 'ｘ', 'x') AS slug,
      replace(replace(replace(replace(title, 'ｕ', 'u'), 'ｖ', 'v'), 'ｗ', 'w'), 'ｘ', 'x') AS title,
      replace(replace(replace(replace(description, 'ｕ', 'u'), 'ｖ', 'v'), 'ｗ', 'w'), 'ｘ', 'x') AS description,
      replace(replace(replace(replace(facets, 'ｕ', 'u'), 'ｖ', 'v'), 'ｗ', 'w'), 'ｘ', 'x') AS facets
    FROM catalog_search_normalization_15
  ),
  catalog_search_normalization_17 AS (
    SELECT
      item_id, kind,
      replace(replace(slug, 'ｙ', 'y'), 'ｚ', 'z') AS slug,
      replace(replace(title, 'ｙ', 'y'), 'ｚ', 'z') AS title,
      replace(replace(description, 'ｙ', 'y'), 'ｚ', 'z') AS description,
      replace(replace(facets, 'ｙ', 'y'), 'ｚ', 'z') AS facets
    FROM catalog_search_normalization_16
  ),
  catalog_search_transliteration_1 AS (
    SELECT
      item_id, kind, slug, title, description, facets,
      replace(replace(replace(replace(replace(replace(replace(replace(slug, 'щ', 'shch'), 'Щ', 'shch'), 'ш', 'sh'), 'Ш', 'sh'), 'ч', 'ch'), 'Ч', 'ch'), 'ц', 'c'), 'Ц', 'c') AS latin_slug,
      replace(replace(replace(replace(replace(replace(replace(replace(title, 'щ', 'shch'), 'Щ', 'shch'), 'ш', 'sh'), 'Ш', 'sh'), 'ч', 'ch'), 'Ч', 'ch'), 'ц', 'c'), 'Ц', 'c') AS latin_title,
      replace(replace(replace(replace(replace(replace(replace(replace(description, 'щ', 'shch'), 'Щ', 'shch'), 'ш', 'sh'), 'Ш', 'sh'), 'ч', 'ch'), 'Ч', 'ch'), 'ц', 'c'), 'Ц', 'c') AS latin_description,
      replace(replace(replace(replace(replace(replace(replace(replace(facets, 'щ', 'shch'), 'Щ', 'shch'), 'ш', 'sh'), 'Ш', 'sh'), 'ч', 'ch'), 'Ч', 'ch'), 'ц', 'c'), 'Ц', 'c') AS latin_facets
    FROM catalog_search_normalization_17
  ),
  catalog_search_transliteration_2 AS (
    SELECT
      item_id, kind, slug, title, description, facets,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_slug, 'ё', 'yo'), 'Ё', 'yo'), 'ю', 'yu'), 'Ю', 'yu'), 'я', 'ya'), 'Я', 'ya'), 'е', 'ye'), 'Е', 'ye') AS latin_slug,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_title, 'ё', 'yo'), 'Ё', 'yo'), 'ю', 'yu'), 'Ю', 'yu'), 'я', 'ya'), 'Я', 'ya'), 'е', 'ye'), 'Е', 'ye') AS latin_title,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_description, 'ё', 'yo'), 'Ё', 'yo'), 'ю', 'yu'), 'Ю', 'yu'), 'я', 'ya'), 'Я', 'ya'), 'е', 'ye'), 'Е', 'ye') AS latin_description,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_facets, 'ё', 'yo'), 'Ё', 'yo'), 'ю', 'yu'), 'Ю', 'yu'), 'я', 'ya'), 'Я', 'ya'), 'е', 'ye'), 'Е', 'ye') AS latin_facets
    FROM catalog_search_transliteration_1
  ),
  catalog_search_transliteration_3 AS (
    SELECT
      item_id, kind, slug, title, description, facets,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_slug, 'ж', 'j'), 'Ж', 'j'), 'х', 'h'), 'Х', 'h'), 'а', 'a'), 'А', 'a'), 'б', 'b'), 'Б', 'b') AS latin_slug,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_title, 'ж', 'j'), 'Ж', 'j'), 'х', 'h'), 'Х', 'h'), 'а', 'a'), 'А', 'a'), 'б', 'b'), 'Б', 'b') AS latin_title,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_description, 'ж', 'j'), 'Ж', 'j'), 'х', 'h'), 'Х', 'h'), 'а', 'a'), 'А', 'a'), 'б', 'b'), 'Б', 'b') AS latin_description,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_facets, 'ж', 'j'), 'Ж', 'j'), 'х', 'h'), 'Х', 'h'), 'а', 'a'), 'А', 'a'), 'б', 'b'), 'Б', 'b') AS latin_facets
    FROM catalog_search_transliteration_2
  ),
  catalog_search_transliteration_4 AS (
    SELECT
      item_id, kind, slug, title, description, facets,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_slug, 'в', 'v'), 'В', 'v'), 'г', 'g'), 'Г', 'g'), 'д', 'd'), 'Д', 'd'), 'э', 'e'), 'Э', 'e') AS latin_slug,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_title, 'в', 'v'), 'В', 'v'), 'г', 'g'), 'Г', 'g'), 'д', 'd'), 'Д', 'd'), 'э', 'e'), 'Э', 'e') AS latin_title,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_description, 'в', 'v'), 'В', 'v'), 'г', 'g'), 'Г', 'g'), 'д', 'd'), 'Д', 'd'), 'э', 'e'), 'Э', 'e') AS latin_description,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_facets, 'в', 'v'), 'В', 'v'), 'г', 'g'), 'Г', 'g'), 'д', 'd'), 'Д', 'd'), 'э', 'e'), 'Э', 'e') AS latin_facets
    FROM catalog_search_transliteration_3
  ),
  catalog_search_transliteration_5 AS (
    SELECT
      item_id, kind, slug, title, description, facets,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_slug, 'з', 'z'), 'З', 'z'), 'и', 'i'), 'И', 'i'), 'й', 'yy'), 'Й', 'yy'), 'к', 'k'), 'К', 'k') AS latin_slug,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_title, 'з', 'z'), 'З', 'z'), 'и', 'i'), 'И', 'i'), 'й', 'yy'), 'Й', 'yy'), 'к', 'k'), 'К', 'k') AS latin_title,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_description, 'з', 'z'), 'З', 'z'), 'и', 'i'), 'И', 'i'), 'й', 'yy'), 'Й', 'yy'), 'к', 'k'), 'К', 'k') AS latin_description,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_facets, 'з', 'z'), 'З', 'z'), 'и', 'i'), 'И', 'i'), 'й', 'yy'), 'Й', 'yy'), 'к', 'k'), 'К', 'k') AS latin_facets
    FROM catalog_search_transliteration_4
  ),
  catalog_search_transliteration_6 AS (
    SELECT
      item_id, kind, slug, title, description, facets,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_slug, 'л', 'l'), 'Л', 'l'), 'м', 'm'), 'М', 'm'), 'н', 'n'), 'Н', 'n'), 'о', 'o'), 'О', 'o') AS latin_slug,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_title, 'л', 'l'), 'Л', 'l'), 'м', 'm'), 'М', 'm'), 'н', 'n'), 'Н', 'n'), 'о', 'o'), 'О', 'o') AS latin_title,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_description, 'л', 'l'), 'Л', 'l'), 'м', 'm'), 'М', 'm'), 'н', 'n'), 'Н', 'n'), 'о', 'o'), 'О', 'o') AS latin_description,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_facets, 'л', 'l'), 'Л', 'l'), 'м', 'm'), 'М', 'm'), 'н', 'n'), 'Н', 'n'), 'о', 'o'), 'О', 'o') AS latin_facets
    FROM catalog_search_transliteration_5
  ),
  catalog_search_transliteration_7 AS (
    SELECT
      item_id, kind, slug, title, description, facets,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_slug, 'п', 'p'), 'П', 'p'), 'р', 'r'), 'Р', 'r'), 'с', 's'), 'С', 's'), 'т', 't'), 'Т', 't') AS latin_slug,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_title, 'п', 'p'), 'П', 'p'), 'р', 'r'), 'Р', 'r'), 'с', 's'), 'С', 's'), 'т', 't'), 'Т', 't') AS latin_title,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_description, 'п', 'p'), 'П', 'p'), 'р', 'r'), 'Р', 'r'), 'с', 's'), 'С', 's'), 'т', 't'), 'Т', 't') AS latin_description,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_facets, 'п', 'p'), 'П', 'p'), 'р', 'r'), 'Р', 'r'), 'с', 's'), 'С', 's'), 'т', 't'), 'Т', 't') AS latin_facets
    FROM catalog_search_transliteration_6
  ),
  catalog_search_transliteration_8 AS (
    SELECT
      item_id, kind, slug, title, description, facets,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_slug, 'у', 'u'), 'У', 'u'), 'ф', 'f'), 'Ф', 'f'), 'ө', 'q'), 'Ө', 'q'), 'ү', 'w'), 'Ү', 'w') AS latin_slug,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_title, 'у', 'u'), 'У', 'u'), 'ф', 'f'), 'Ф', 'f'), 'ө', 'q'), 'Ө', 'q'), 'ү', 'w'), 'Ү', 'w') AS latin_title,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_description, 'у', 'u'), 'У', 'u'), 'ф', 'f'), 'Ф', 'f'), 'ө', 'q'), 'Ө', 'q'), 'ү', 'w'), 'Ү', 'w') AS latin_description,
      replace(replace(replace(replace(replace(replace(replace(replace(latin_facets, 'у', 'u'), 'У', 'u'), 'ф', 'f'), 'Ф', 'f'), 'ө', 'q'), 'Ө', 'q'), 'ү', 'w'), 'Ү', 'w') AS latin_facets
    FROM catalog_search_transliteration_7
  ),
  catalog_search_transliteration_9 AS (
    SELECT
      item_id, kind, slug, title, description, facets,
      replace(replace(replace(replace(replace(replace(latin_slug, 'ы', 'y'), 'Ы', 'y'), 'ь', 'ь'), 'Ь', 'ь'), 'ъ', ''''), 'Ъ', '''') AS latin_slug,
      replace(replace(replace(replace(replace(replace(latin_title, 'ы', 'y'), 'Ы', 'y'), 'ь', 'ь'), 'Ь', 'ь'), 'ъ', ''''), 'Ъ', '''') AS latin_title,
      replace(replace(replace(replace(replace(replace(latin_description, 'ы', 'y'), 'Ы', 'y'), 'ь', 'ь'), 'Ь', 'ь'), 'ъ', ''''), 'Ъ', '''') AS latin_description,
      replace(replace(replace(replace(replace(replace(latin_facets, 'ы', 'y'), 'Ы', 'y'), 'ь', 'ь'), 'Ь', 'ь'), 'ъ', ''''), 'Ъ', '''') AS latin_facets
    FROM catalog_search_transliteration_8
  )
SELECT
  item_id,
  kind,
  'krilleer-cyr-lat-v1' AS document_version,
  json_array('krilleer-cyr-lat-v1', item_id, kind, slug, title, description, facets) AS fingerprint,
  slug,
  title,
  description,
  facets,
  latin_slug,
  latin_title,
  latin_description,
  latin_facets
FROM catalog_search_transliteration_9;
--> statement-breakpoint
INSERT INTO catalog_search(item_id, kind, document_version, fingerprint, slug, title, description, facets, latin_slug, latin_title, latin_description, latin_facets) SELECT item_id, kind, document_version, fingerprint, slug, title, description, facets, latin_slug, latin_title, latin_description, latin_facets FROM catalog_search_documents;
--> statement-breakpoint
CREATE VIEW catalog_search_diagnostics AS
SELECT
  (SELECT count(*) FROM catalog_search_documents) AS canonical_count,
  (SELECT count(*) FROM catalog_search) AS projection_count,
  (SELECT count(*) FROM catalog_search_documents expected WHERE NOT EXISTS (SELECT 1 FROM catalog_search actual WHERE actual.item_id = expected.item_id)) AS missing_count,
  (SELECT count(*) FROM catalog_search actual WHERE NOT EXISTS (SELECT 1 FROM catalog_search_documents expected WHERE expected.item_id = actual.item_id)) AS orphan_count,
  (SELECT count(*) FROM (SELECT item_id FROM catalog_search GROUP BY item_id HAVING count(*) > 1)) AS duplicate_count,
  (SELECT count(*) FROM catalog_search_documents expected JOIN catalog_search actual ON actual.item_id = expected.item_id WHERE actual.document_version IS NOT expected.document_version OR actual.fingerprint IS NOT expected.fingerprint OR actual.kind IS NOT expected.kind OR actual.slug IS NOT expected.slug OR actual.title IS NOT expected.title OR actual.description IS NOT expected.description OR actual.facets IS NOT expected.facets OR actual.latin_slug IS NOT expected.latin_slug OR actual.latin_title IS NOT expected.latin_title OR actual.latin_description IS NOT expected.latin_description OR actual.latin_facets IS NOT expected.latin_facets) AS mismatched_count;
--> statement-breakpoint
CREATE TABLE catalog_search_refresh (item_id text PRIMARY KEY NOT NULL);
--> statement-breakpoint
CREATE TRIGGER catalog_search_refresh_item AFTER INSERT ON catalog_search_refresh BEGIN
  DELETE FROM catalog_search WHERE item_id = NEW.item_id;
  INSERT INTO catalog_search(item_id, kind, document_version, fingerprint, slug, title, description, facets, latin_slug, latin_title, latin_description, latin_facets) SELECT item_id, kind, document_version, fingerprint, slug, title, description, facets, latin_slug, latin_title, latin_description, latin_facets FROM catalog_search_documents WHERE item_id = NEW.item_id;
  DELETE FROM catalog_search_refresh WHERE item_id = NEW.item_id;
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_catalog_insert AFTER INSERT ON catalog_items BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) VALUES (NEW.id);
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_catalog_update AFTER UPDATE OF slug, state, name, description ON catalog_items BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) VALUES (NEW.id);
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_catalog_delete AFTER DELETE ON catalog_items BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) VALUES (OLD.id);
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_categories_membership_insert AFTER INSERT ON catalog_item_categories BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) VALUES (NEW.catalog_item_id);
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_categories_membership_delete AFTER DELETE ON catalog_item_categories BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) VALUES (OLD.catalog_item_id);
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_collections_membership_insert AFTER INSERT ON catalog_item_collections BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) VALUES (NEW.catalog_item_id);
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_collections_membership_delete AFTER DELETE ON catalog_item_collections BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) VALUES (OLD.catalog_item_id);
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_tags_membership_insert AFTER INSERT ON catalog_item_tags BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) VALUES (NEW.catalog_item_id);
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_tags_membership_delete AFTER DELETE ON catalog_item_tags BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) VALUES (OLD.catalog_item_id);
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_categories_update AFTER UPDATE OF name, state, position ON categories BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) SELECT DISTINCT catalog_item_id FROM catalog_item_categories WHERE category_id = NEW.id;
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_collections_update AFTER UPDATE OF name, state ON collections BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) SELECT DISTINCT catalog_item_id FROM catalog_item_collections WHERE collection_id = NEW.id;
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_tags_update AFTER UPDATE OF label, state ON tags BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) SELECT DISTINCT catalog_item_id FROM catalog_item_tags WHERE tag_id = NEW.id;
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_option_groups_update AFTER UPDATE OF state, position ON option_groups BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) SELECT DISTINCT product_id FROM variants WHERE product_id = NEW.product_id;
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_option_values_update AFTER UPDATE OF label, state, position ON option_values BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) SELECT DISTINCT variant.product_id FROM variant_option_values membership JOIN variants variant ON variant.id = membership.variant_id WHERE membership.option_value_id = NEW.id;
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_variants_insert AFTER INSERT ON variants BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) VALUES (NEW.product_id);
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_variants_update AFTER UPDATE OF state, product_id ON variants BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) VALUES (OLD.product_id);
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) SELECT NEW.product_id WHERE NEW.product_id <> OLD.product_id;
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_variants_delete AFTER DELETE ON variants BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) VALUES (OLD.product_id);
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_variant_option_values_insert AFTER INSERT ON variant_option_values BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) SELECT product_id FROM variants WHERE id = NEW.variant_id;
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_variant_option_values_update AFTER UPDATE OF variant_id, option_value_id ON variant_option_values BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) SELECT DISTINCT product_id FROM variants WHERE id IN (OLD.variant_id, NEW.variant_id);
END;
--> statement-breakpoint
CREATE TRIGGER catalog_search_variant_option_values_delete AFTER DELETE ON variant_option_values BEGIN
  INSERT OR IGNORE INTO catalog_search_refresh(item_id) SELECT product_id FROM variants WHERE id = OLD.variant_id;
END;
