import { basicVariants, keyFor, normalize, transliterateStrictAscii } from "../src/transliteration";

type Product = { name: string; category: string; tags: string; sku: string; price: number };
const words = [
  ["Ноосон цамц", "HV-Ө-001", "Хувцас", "ноос, дулаан"], ["Өдөр тутмын цүнх", "HV-Ц-002", "Цүнх", "өдөр, арьс"], ["Үсний боолт", "HV-Ү-003", "Гоо сайхан", "үс, даавуу"], ["Ёслолын даашинз", "HV-Я-004", "Хувцас", "ёслол, торго"], ["Ердийн даашинз", "HV-Е-005", "Хувцас", "даашинз, өдөр"], ["Хүүхдийн хүрэм", "HV-Х-006", "Хүүхэд", "хүүхэд, дулаан"], ["Цагаан цамц", "HV-Ц-007", "Хувцас", "цагаан, даавуу"], ["Чанартай оймс", "HV-Ч-008", "Хувцас", "чанар, оймс"], ["Шаргал ороолт", "HV-Ш-009", "Дагалдах", "шаргал, ноос"], ["Жижиг түрийвч", "HV-Ж-010", "Дагалдах", "жижиг, арьс"],
  ["Ягаан малгай", "HV-Я-011", "Дагалдах", "ягаан, өвөл"], ["Юбка хар", "HV-Ю-012", "Хувцас", "юбка, хар"], ["Хөх ноолууран цамц", "HV-Х-013", "Хувцас", "хөх, ноолуур"], ["Өвлийн гутал", "HV-Ө-014", "Гутал", "өвөл, арьс"], ["Үүргэвч аяллын", "HV-Ү-015", "Цүнх", "үүргэвч, аялал"], ["Ёотон амттан", "HV-Ё-016", "Хүнс", "амттан, ёотон"], ["Цайны аяга", "HV-Ц-017", "Гэр ахуй", "цай, аяга"], ["Чулуун аяга", "HV-Ч-018", "Гэр ахуй", "чулуу, аяга"], ["Шилэн сав", "HV-Ш-019", "Гэр ахуй", "шил, сав"], ["Жимсний сагс", "HV-Ж-020", "Гэр ахуй", "жимс, сагс"],
  ["Янзын лаа", "HV-Я-021", "Гэр ахуй", "лаа, гэрэл"], ["Юмны хайрцаг", "HV-Ю-022", "Гэр ахуй", "хайрцаг, хадгалалт"], ["Ногоон цай", "HV-Н-023", "Хүнс", "ногоон, цай"], ["Өргөст хэмх", "HV-Ө-024", "Хүнс", "ногоо, өргөст"], ["Үхрийн мах", "HV-Ү-025", "Хүнс", "мах, үхэр"], ["Ёроолын цэвэрлэгч", "HV-Ё-026", "Гэр ахуй", "цэвэр, ёроол"], ["Цэвэр усны сав", "HV-Ц-027", "Гэр ахуй", "ус, цэвэр"], ["Чихэрлэг жимс", "HV-Ч-028", "Хүнс", "чихэр, жимс"], ["Шарсан кофе", "HV-Ш-029", "Хүнс", "кофе, шарсан"], ["Жимсний цай", "HV-Ж-030", "Хүнс", "жимс, цай"],
  ["Яргай загас", "HV-Я-031", "Хүнс", "загас, яргай"], ["Юүлүүр гал тогоо", "HV-Ю-032", "Гэр ахуй", "гал тогоо, юүлүүр"], ["Ноосон-цамц", "HV-Ө-033", "Хувцас", "ноос, цамц"], ["Өргөн мөртэй цүнх", "HV-Ө-034", "Цүнх", "өргөн, мөр"], ["Үзэгний сав", "HV-Ү-035", "Бичиг хэрэг", "үзэг, сав"], ["Ёслолын бүс", "HV-Ё-036", "Дагалдах", "ёслол, бүс"], ["Цахилгаан данх", "HV-Ц-037", "Гэр ахуй", "данх, цахилгаан"], ["Чийгшүүлэгч тос", "HV-Ч-038", "Гоо сайхан", "тос, чийг"], ["Шүдний сойз", "HV-Ш-039", "Гоо сайхан", "шүд, сойз"], ["Жижиг цэцгийн сав", "HV-Ж-040", "Гэр ахуй", "цэцэг, сав"]
] satisfies readonly [string, string, string, string][];
const sql = (value: string): string => `'${value.replaceAll("'", "''")}'`;
const rows = words.map(([name, sku, category, tags], index): Product => ({ name, sku, category, tags, price: 12000 + index * 1750 }));
const statements = ["DELETE FROM product_search_tiered;", "DELETE FROM product_search;", "DELETE FROM products;", ...rows.flatMap((product, index) => {
  const strict = keyFor(`${product.name} ${product.category} ${product.tags} ${product.sku}`, "strict");
  const basic = keyFor(`${product.name} ${product.category} ${product.tags} ${product.sku}`, "basic");
  const searchable = `${product.name} ${product.category} ${product.tags} ${product.sku}`;
  const nativeKey = normalize(searchable);
  const strictAsciiKey = transliterateStrictAscii(searchable);
  const basicKey = basicVariants(searchable).join(" ");
  const skuNormalized = normalize(product.sku).replaceAll(" ", "").replaceAll("-", "");
  return [`INSERT INTO products (id, sku, sku_normalized, name, category, tags, price_mnt, strict_key, basic_key) VALUES (${index + 1}, ${sql(product.sku)}, ${sql(skuNormalized)}, ${sql(product.name)}, ${sql(product.category)}, ${sql(product.tags)}, ${product.price}, ${sql(strict)}, ${sql(basic)});`, `INSERT INTO product_search (product_id, name, category, tags, sku, strict_key, basic_key) VALUES (${index + 1}, ${sql(keyFor(product.name, "strict"))}, ${sql(keyFor(product.category, "strict"))}, ${sql(keyFor(product.tags, "strict"))}, ${sql(keyFor(product.sku, "strict"))}, ${sql(strict)}, ${sql(basic)});`, `INSERT INTO product_search_tiered (product_id, native_key, strict_key, basic_key, sku_key) VALUES (${index + 1}, ${sql(nativeKey)}, ${sql(strictAsciiKey)}, ${sql(basicKey)}, ${sql(skuNormalized)});`]; })];
await Bun.write(new URL("../seed.sql", import.meta.url), `${statements.join("\n")}\n`);
console.log(`wrote ${rows.length} synthetic products`);
